### ISSUE TITLE
react-native link does not work correctly

### ISSUE THREAD

**Issue by inferusvv** [AlexanderZaytsev/react-native-i18n#43]
On iOS all fine. If device lang is ru then I see this locale. On android it is empty string. I've tested it on virtual device and real device.

See next code:

```
import I18n from 'react-native-i18n';
console.log('I18n', I18n);
```

<img width="852" alt="2016-10-19 16 32 08" src="https://cloud.githubusercontent.com/assets/3227120/19520648/9d69375c-9619-11e6-98f3-838e9ff6aa50.png">

**Comment by Dakoso** [comment]
+1 Same problem here

**Comment by inferusvv** [comment]
I think, I need to add that I use Android 6.0

**Comment by denvers** [comment]
I use `I18n.currentLocale()` which works for me.

**Comment by inferusvv** [comment]
@denvers For me it returns "en", while phone is in "ru"

**Comment by inferusvv** [comment]
FIXED! Just don't use automatic setup via "link". Check your MainApplication.java for import of library and it's initializaition

**Comment by leventebalogh** [comment]
@inferusvv So you mean that the `react-native link` did not set it up correctly and you needed to correct it manually?

**Comment by inferusvv** [comment]
@leventebalogh yes, it doesn't work

**Comment by mmazzarolo** [comment]
@inferusvv weird, which version on rn? 
it works for me

**Comment by dccarmo** [comment]
This should be re-opened, it's still an issue and @inferusvv's solution is the correct one. Maybe the recipe for `rnpm link` needs to be updated?

**Comment by AnagramEngineering** [comment]
Same here, 

I18n.currentLocale() (returns 'en' but it should be 'de') 
ReactNativeI18n.locale returns '' but should be 'de'

**Comment by Naoto-Ida** [comment]
Doesn't work for me either on RN v0.40.0 (iOS).
My locale is `en-JP`. I have `fallbacks` to `true`, so event when I'm lacking `en-JP` it should default to `en` yet shows the *missing* error.

**Comment by wachunei** [comment]
I'm getting an empty locale too on iOS.
<img width="586" alt="screen shot 2017-01-25 at 10 18 58 am" src="https://cloud.githubusercontent.com/assets/1024246/22291947/bf21c452-e2e7-11e6-9ad9-d27250258034.png">

**Comment by mmazzarolo** [comment]
Hey there, can you provide some more info on the version of RN you're using?  
I tried it on a bunch of different flavours and it worked correctly with `react-native link`.

**Comment by wachunei** [comment]
Im using RN 0.40, maybe it didn't link correctly? Is there a way to unlink and link again?

**Comment by mmazzarolo** [comment]
Are you on `i18n@1.0.0`? You can unlink with `react-native unlink react-native-i18n`

**Comment by wachunei** [comment]
Yes I am using 1.0.0.

I've unlink and link again and it is still returning undefined.

**Comment by dkpalmer** [comment]
We encountered the same result as @wachunei, where we had to manually added lib for iOS.

RN 0.42.0, react-native-i18n 1.0.0.

**Comment by jjhesk** [comment]
@wachunei how do we add and link the library manuallly on iOS?

**Comment by wachunei** [comment]
@jjhesk open ios/*.xcodproj project, then click on your project in the Project Navigator sidebar, click on Build Phases and expand Link Binary With Libraries section, `libRNI18n.a` should not be listed. Expand Libraries folder in Project Navigator, then RNI18n.xcodeproj » Products, grab `libRNI18n.a` and drop it into the Link Binary With Libraries list. You're done. [Here's the official guide to Linking Libraries in iOS](https://facebook.github.io/react-native/docs/linking-libraries-ios.html)

**Comment by mmazzarolo** [comment]
Hey all, I've been a bit busy lately.  
Does anyone know what can be the source of this linking bug? It seems to happen since 0.40 🤔

**Comment by wachunei** [comment]
I'm kinda lost here, how do packages tell `react-native link` what to link to project?

**Comment by mmazzarolo** [comment]
Same for me, I created some native libraries in the past ([like this one](https://github.com/mmazzarolo/react-native-beacons-android)) but `react-native link` has always worked out of the box.

**Comment by flq** [comment]
Maybe it has to do with this, maybe not - I have tried to test my translations on the ios simulator on my MBP - what I did is go to settings and change the language and region to german/germany (I have got a 'de'-translation block), alas, nothing seems to happen. What are the prerequisites for this to work?

**Comment by chemitaxis** [comment]
Ok, I have solved with a workaround (see this open issue by me): https://github.com/AlexanderZaytsev/react-native-i18n/issues/53

You can add this (tested on iOS emulator) to solve the locale undefined or empty:
I18n.locale = I18n.currentLocale(); 

https://github.com/AlexanderZaytsev/react-native-i18n/issues/43

**Comment by wachunei** [comment]
Hey guys, I'm setting up a new project with this library and bug is still happening, just had to drag and drop `libRNI18n.a` manually to linked libraries. Android seems to work fine.

I think this is a non-minor bug and should me mentioned in `README.md`, because everyone is going to fall back to manual installation, not after a few tries and losing some time figure things out.

I have not found a way to specify `react-native link` exactly what to do to link this library correctly.

@mmazzarolo you're welcome, I'm glad to help.

**Comment by zoontek** [comment]
@wachunei I added a warning in the `README.md`. I investigate on the problem.

**Comment by zoontek** [comment]
Can you give a try on the v2.0.0? It should be fixed now 😃

**Comment by inferusvv** [comment]
@zoontek Some hours ago upgraded library. All fine 👍
