### ISSUE TITLE
I18n breaks React-Native Android Apps

### ISSUE THREAD

**Issue by BerndWessels** [AlexanderZaytsev/react-native-i18n#6]
Hi
Using react-native-i18n in an React-Native Android app breaks it with the following error:

    undefined is not an object (evaluating 'RNI18n.locale')

Since Ract-Native Android is now open-sourced and this is currently the defacto i18n component for react-native it would be great if you guys could fix this soon.

Thank you
Bernd

**Comment by phlegx** [comment]
:+1:  Same problem!

**Comment by webwelten** [comment]
+1

**Comment by eyaleizenberg** [comment]
+1

**Comment by SteveMellross** [comment]
+1

**Comment by liesislukas** [comment]
+1 looking forward for this!

**Comment by fxhereng** [comment]
I tried as well this: https://www.npmjs.com/package/react-native-i18n-complete for Android, to get it working, I had to change:
    var I18n = require('react-native-i18n');
in
   var I18n = require("react-native-i18n-complete");

Hope it can help

**Comment by SalahAdDin** [comment]
:+1:

**Comment by AlexanderZaytsev** [comment]
Should be fixed in 0.0.7

**Comment by DimitrK** [comment]
I am getting the same error
![image](https://cloud.githubusercontent.com/assets/4526699/13366163/3c1526e6-dce2-11e5-8d72-ddd2b4d5b8d3.png)

**Comment by anttitakalahti** [comment]
You need to restart the emulator to allow the linking to work. This got rid of the underfined is not an object problem error for me when working on an iOS app.

**Comment by DimitrK** [comment]
I am still unable to get it working even after restarting the emulator. I cleaned data and uninstalled the app before restart as well. Any suggestions ?

**Comment by austinkelleher** [comment]
+1 I am still getting this error on 0.0.8 too.

**Comment by yakovlevyuri** [comment]
+1 The same here

**Comment by sheburdos** [comment]
Had same issue. In some reason if the module is installed using **_rnpm_**:

rnpm install react-native-i18n" to install it. After removing module and using:

it has problems with RNI19n.locale. After reinstalling module using:

npm install react-native-i18n
rnpm link react-native-i18n

everyting works. At least on Android emulator

**Comment by zvona** [comment]
I got this working with manual install instructions (https://github.com/AlexanderZaytsev/react-native-i18n#android). Linking with `rnpm link react-native-i18n` worked only with iOS.

**Comment by nicosefer** [comment]
the problem is that these lines are missing in the settings.gradle file 
`include ':react-native-i18n'
project(':react-native-i18n').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-i18n/android')
`

**Comment by mortik** [comment]
I needed to add the following into the MainApplication.java under app/src/main/com/your-app/MainApplication.java 

``` 
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        ...
        new ReactNativeI18n()
      );
    }
```

and also import the package at the top of the file:
```
import com.i18n.reactnativei18n.ReactNativeI18n;
```

**Comment by keeleycarrigan** [comment]
@mortik Thanks!

That worked for me too. I had to add that after upgrading to React Native 0.30. Also had to redo all my FB SDK stuff too...blurg.
